In [17]:
from sklearn import preprocessing
import numpy as np

data = np.array([[2.2, 5.9, -1.8,1.1], [5.4, -3.2, -5.1,1.1], [-1.9, 4.2, 3.2,1.1]])

In [18]:
binData= preprocessing.Binarizer(threshold=1.5).transform(data)

In [19]:
print(binData)

[[ 1.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  1.  0.]]

In [21]:
mean_data= data.mean(axis=0)
std= data.std(axis=0)
print(mean_data,std)

[ 1.9         2.3        -1.23333333  1.1       ] [ 2.98775278  3.95052739  3.41207008  0.        ]

In [22]:
scaled_data=preprocessing.scale(data)

In [24]:
print(scaled_data.mean(axis=0),scaled_data.std(axis=0))

[  0.00000000e+00   0.00000000e+00   7.40148683e-17   0.00000000e+00] [ 1.  1.  1.  0.]

SCALING

In [26]:
minmax= preprocessing.MinMaxScaler(feature_range=(0,0.5))
data_minmax= minmax.fit_transform(data)
print(data_minmax)

[[ 0.28082192  0.5         0.19879518  0.        ]
 [ 0.5         0.          0.          0.        ]
 [ 0.          0.40659341  0.5         0.        ]]

Normalization

In [27]:
dataL1= preprocessing.normalize(data,norm='l1')
dataL2= preprocessing.normalize(data,norm='l2')
print(dataL1)
print(dataL2)

[[ 0.2         0.53636364 -0.16363636  0.1       ]
 [ 0.36486486 -0.21621622 -0.34459459  0.07432432]
 [-0.18269231  0.40384615  0.30769231  0.10576923]]
[[ 0.33128623  0.88844944 -0.27105237  0.16564312]
 [ 0.66159383 -0.3920556  -0.62483862  0.13476911]
 [-0.33226127  0.73447229  0.55959793  0.19236179]]

LABEL ENCODING



NEW THING

In [28]:
labels=['satosa','mamosa','samosas']
encoder=preprocessing.LabelEncoder()
encoder.fit(labels)

for i,item in enumerate(encoder.classes_):
    print(i,item)

0 mamosa
1 samosas
2 satosa

In [31]:
import pandas as pd
from IPython.display import display

data = pd.read_csv('smsspam.txt', header=None, index_col=False, names=['age', 'workclass', 'fnlwgt', 'education', 
                                                                      'education-num', 'marital-status', 'occupation', 
                                                                      'relationship', 'race', 'gender', 'capital-gain', 
                                                                      'capital-loss', 'hours-per-week', 'native-country', 
                                                                      'income'])

In [32]:
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K

In [33]:
print(data.columns)
dummies=pd.get_dummies(data)
print(dummies.columns)

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')
Index(['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss',
       'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov',
       'workclass_ Local-gov', 'workclass_ Never-worked',
       ...
       'native-country_ Scotland', 'native-country_ South',
       'native-country_ Taiwan', 'native-country_ Thailand',
       'native-country_ Trinadad&Tobago', 'native-country_ United-States',
       'native-country_ Vietnam', 'native-country_ Yugoslavia',
       'income_ <=50K', 'income_ >50K'],
      dtype='object', length=109)

In [34]:
data = data[['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income']]
display(data)

,age,workclass,education,gender,hours-per-week,occupation,income
0,39,State-gov,Bachelors,Male,40.0,Adm-clerical,<=50K
1,50,Self-emp-not-inc,Bachelors,Male,13.0,Exec-managerial,<=50K
2,38,Private,HS-grad,Male,40.0,Handlers-cleaners,<=50K
3,53,Private,11th,Male,40.0,Handlers-cleaners,<=50K
4,28,Private,Bachelors,Female,40.0,Prof-specialty,<=50K
5,37,Private,Masters,Female,40.0,Exec-managerial,<=50K
6,49,Private,9th,Female,16.0,Other-service,<=50K
7,52,Self-emp-not-inc,HS-grad,Male,45.0,Exec-managerial,>50K
8,31,Private,Masters,Female,50.0,Prof-specialty,>50K
9,42,Private,Bachelors,Male,40.0,Exec-managerial,>50K
10,37,Private,Some-college,Male,80.0,Exec-managerial,>50K
11,30,State-gov,Bachelors,Male,40.0,Prof-specialty,>50K
12,23,Private,Bachelors,Female,30.0,Adm-clerical,<=50K
13,32,Private,Assoc-acdm,Male,50.0,Sales,<=50K
14,40,Private,Assoc-voc,Male,40.0,Craft-repair,>50K
15,34,Private,7th-8th,Male,45.0,Transport-moving,<=50K
16,25,Self-emp-not-inc,HS-grad,Male,35.0,Farming-fishing,<=50K
17,32,Private,HS-grad,Male,40.0,Machine-op-inspct,<=50K
18,38,Private,11th,Male,50.0,Sales,<=50K
19,43,Self-emp-not-inc,Masters,Female,45.0,Exec-managerial,>50K
20,40,Private,Doctorate,Male,60.0,Prof-specialty,>50K
21,54,Private,HS-grad,Female,20.0,Other-service,<=50K
22,35,Federal-gov,9th,Male,40.0,Farming-fishing,<=50K
23,43,Private,11th,Male,40.0,Transport-moving,<=50K
24,59,Private,HS-grad,Female,40.0,Tech-support,<=50K
25,56,Local-gov,Bachelors,Male,40.0,Tech-support,>50K
26,19,Private,HS-grad,Male,40.0,Craft-repair,<=50K
27,54,?,Some-college,Male,60.0,?,>50K
28,39,Private,HS-grad,Male,80.0,Exec-managerial,<=50K
29,49,Private,HS-grad,Male,40.0,Craft-repair,<=50K
...,...,...,...,...,...,...,...
12863,44,Federal-gov,HS-grad,Female,40.0,Craft-repair,<=50K
12864,19,Self-emp-not-inc,Some-college,Female,25.0,Other-service,<=50K
12865,59,Private,Masters,Female,35.0,Craft-repair,<=50K
12866,50,Private,HS-grad,Male,40.0,Other-service,<=50K
12867,35,Federal-gov,Bachelors,Male,40.0,Craft-repair,>50K
12868,46,Federal-gov,Some-college,Male,40.0,Machine-op-inspct,<=50K
12869,18,Private,Some-college,Male,35.0,Sales,<=50K
12870,32,Private,5th-6th,Male,40.0,Machine-op-inspct,<=50K
12871,32,Private,Assoc-voc,Female,40.0,Other-service,<=50K
12872,39,Private,HS-grad,Male,40.0,Craft-repair,>50K
12873,25,Private,HS-grad,Female,40.0,Craft-repair,<=50K
12874,30,Private,Masters,Male,60.0,Exec-managerial,>50K
12875,37,Private,Bachelors,Male,40.0,Tech-support,>50K
12876,38,Self-emp-inc,Some-college,Male,80.0,Exec-managerial,>50K
12877,36,Private,Assoc-acdm,Female,37.0,Other-service,<=50K
12878,56,Private,Some-college,Male,40.0,Sales,>50K
12879,35,Federal-gov,Bachelors,Male,40.0,Adm-clerical,>50K
12880,56,Private,HS-grad,Male,41.0,Adm-clerical,<=50K
12881,17,Private,10th,Male,14.0,Other-service,<=50K
12882,46,Private,Masters,Male,45.0,Exec-managerial,>50K
12883,56,Private,HS-grad,Female,40.0,Adm-clerical,<=50K
12884,61,State-gov,12th,Male,40.0,Craft-repair,<=50K
12885,25,Private,Some-college,Male,43.0,Sales,<=50K
12886,27,Private,HS-grad,Female,40.0,Machine-op-inspct,<=50K
12887,50,Self-emp-not-inc,HS-grad,Male,30.0,Farming-fishing,<=50K
12888,33,Self-emp-not-inc,Assoc-voc,Male,62.0,Farming-fishing,<=50K
12889,33,Private,Assoc-voc,Male,40.0,Craft-repair,>50K
12890,38,Private,Some-college,Male,60.0,Farming-fishing,<=50K
12891,51,Private,11th,Male,40.0,Machine-op-inspct,<=50K
12892,27,Private,Assoc-acdm,NaN,NaN,NaN,NaN

In [35]:
print(data.columns)
dummies=pd.get_dummies(data)
print(dummies.columns)

Index(['age', 'workclass', 'education', 'gender', 'hours-per-week',
       'occupation', 'income'],
      dtype='object')
Index(['age', 'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov',
       'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private',
       'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc',
       'workclass_ State-gov', 'workclass_ Without-pay', 'education_ 10th',
       'education_ 11th', 'education_ 12th', 'education_ 1st-4th',
       'education_ 5th-6th', 'education_ 7th-8th', 'education_ 9th',
       'education_ Assoc-acdm', 'education_ Assoc-voc', 'education_ Bachelors',
       'education_ Doctorate', 'education_ HS-grad', 'education_ Masters',
       'education_ Preschool', 'education_ Prof-school',
       'education_ Some-college', 'gender_ Female', 'gender_ Male',
       'occupation_ ?', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces',
       'occupation_ Craft-repair', 'occupation_ Exec-managerial',
       'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners',
       'occupation_ Machine-op-inspct', 'occupation_ Other-service',
       'occupation_ Priv-house-serv', 'occupation_ Prof-specialty',
       'occupation_ Protective-serv', 'occupation_ Sales',
       'occupation_ Tech-support', 'occupation_ Transport-moving',
       'income_ <=50K', 'income_ >50K'],
      dtype='object')

In [39]:
features= dummies.ix[:,'age':'occupation_ Transport-moving']
X=features.values
y=dummies['income_ >50K'].values

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test= train_test_split(X,y,random_state=0)
logreg=LogisticRegression()
logreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [41]:
print(logreg.score(X_test,y_test))

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').